from __future__ import annotations

import json

import config
from src.orchestrator.schemas import IntentResult

SYNTHESIS_SYSTEM_PROMPT = """You are a Change Detection & Remote Sensing Synthesis Engine for ISRO's SatQuery AI platform.
You receive quantitative statistics produced by specialist CV engines analyzing Sentinel-1/2 imagery.

TASK:
1. Synthesize a plain-language summary answering the user's query using ONLY the provided statistics.
2. Highlight key risk areas or urban/environmental implications.
3. Provide actionable recommendations for domain experts (disaster mitigation, urban planning, water management).

OUTPUT FORMAT (Markdown):
- **Summary** (1-3 sentences directly answering the user)
- **Quantitative Breakdown** (bullet list with the exact numbers given)
- **Impact & Risks**
- **Recommendations**

Be precise. Never invent numbers not present in the input."""


def _fallback_answer(query: str, intent: str, stats: dict) -> str:
    lines: list[str] = []

    if intent == "SPATIAL_SEGMENTATION":
        feature = stats.get("feature", "feature")
        s = stats.get("segmentation", {})
        lines += [
            f"### Segmentation Result — {feature.title()}",
            f"- Mapped **{s.get('pixels', 0):,} px** (~{s.get('area_km2', 0)} km²) covering "
            f"**{s.get('percent', 0)}%** of the scene in {s.get('num_regions', 0)} region(s).",
            f"- Overlay rendered on the optical base map; legend color marks all {feature} pixels.",
        ]
    elif intent == "CHANGE_DETECTION":
        s = stats.get("change", {})
        lines += [
            "### Change Detection Result",
            f"- Changed area: **{s.get('changed_area_km2', 0)} km²** "
            f"({s.get('change_percent', 0)}% of {s.get('total_area_km2', 0)} km² analyzed).",
            f"- Net signal inside changed zones: **{s.get('net_direction', 'stable')}** "
            f"(T2 vs T1 brightness delta).",
            f"- {s.get('num_change_regions', 0)} distinct change region(s) detected at Otsu threshold "
            f"{s.get('threshold', 0)}.",
        ]
    elif intent == "CROSS_MODAL_FUSION":
        s = stats.get("fusion", {})
        cm = s.get("cross_modal", {})
        lines += [
            "### Cross-Modal Fusion Result (SAR + Optical)",
            f"- Water: {s.get('water', {}).get('area_km2', 0)} km² | Built-up: "
            f"{s.get('built_up', {}).get('area_km2', 0)} km² | Vegetation: "
            f"{s.get('vegetation', {}).get('area_km2', 0)} km².",
            f"- SAR cross-check rejected **{cm.get('sar_rejected_false_positives', 0)} px** "
            f"({cm.get('sar_rejection_percent', 0)}%) of optical-only water false positives.",
        ]
    else:
        lines += ["VQA answer generated by the vision engine."]

    lines.append("\n*Generated offline via deterministic rule engine — connect a GROQ_API_KEY for LLM-grade synthesis.*")
    return "\n".join(lines)


def synthesize(query: str, intent_result: IntentResult, engine_stats: dict) -> tuple[str, str]:
    if config.llm_available():
        try:
            from groq import Groq

            client = Groq(api_key=config.GROQ_API_KEY)

            def jsonable(obj):
                import numpy as np

                if isinstance(obj, dict):
                    return {k: jsonable(v) for k, v in obj.items()}
                if isinstance(obj, (list, tuple)):
                    return [jsonable(v) for v in obj]
                if isinstance(obj, (np.integer,)):
                    return int(obj)
                if isinstance(obj, (np.floating,)):
                    return float(obj)
                return obj

            payload = {
                "user_query": query,
                "intent": intent_result.primary_intent,
                "router_reasoning": intent_result.reasoning,
                "engine_statistics": jsonable(engine_stats),
            }
            completion = client.chat.completions.create(
                model=config.GROQ_TEXT_MODEL,
                temperature=0.3,
                max_tokens=800,
                messages=[
                    {"role": "system", "content": SYNTHESIS_SYSTEM_PROMPT},
                    {"role": "user", "content": json.dumps(payload)},
                ],
            )
            text = completion.choices[0].message.content or ""
            if text.strip():
                return text.strip(), "groq_llm"
        except Exception:
            pass
    return _fallback_answer(query, intent_result.primary_intent, engine_stats), "rule_based"
